// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSGolfDatabas.Database;

#nullable disable

namespace WSGolfDatabas.Migrations
{
    [DbContext(typeof(GolfContext))]
    [Migration("20211222170751_fourth")]
    partial class fourth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WSGolfDatabas.Models.CourseTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("GolfCourse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WSGolfDatabas.Models.ScoreTable", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("CourseIdId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("WeatherIdId")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.HasIndex("CourseIdId");

                    b.HasIndex("WeatherIdId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("WSGolfDatabas.Models.WeatherTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("WSGolfDatabas.Models.ScoreTable", b =>
                {
                    b.HasOne("WSGolfDatabas.Models.CourseTable", "CourseId")
                        .WithMany()
                        .HasForeignKey("CourseIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSGolfDatabas.Models.WeatherTable", "WeatherId")
                        .WithMany()
                        .HasForeignKey("WeatherIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseId");

                    b.Navigation("WeatherId");
                });
#pragma warning restore 612, 618
        }
    }
}
